image: maven:3.8.6-openjdk-18-slim

stages:
  - build
  - test
  - push-docker
  - deploy

build:
  stage: build
  script:
    - echo "Clean the code..."
    - mvn clean
    - echo "Compiling the code..."
    - mvn package -Dmaven.test.skip
    - echo "Compile complete."

test:
  stage: test
  script:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_KEY=$AWS_SECRET_KEY AWS_SQS_QUEUE_ACCOUNT_ID=$AWS_SQS_QUEUE_ACCOUNT_ID AWS_SQS_QUEUE_NAME=$AWS_SQS_QUEUE_NAME AWS_SES_EMAIL_SENDER=$AWS_SES_EMAIL_SENDER mvn test
    - echo "Test OK!"

push-image:
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  stage: push-docker
  dependencies:
    - test
  script:
    - docker build -t nettojulio/ses-sqs-consumer-e8:latest -f Dockerfile .
    - docker push nettojulio/ses-sqs-consumer-e8:latest

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
